## OP Codes
AX = 0xBA  # Alarm Reset
CJ = 0x96  # Start Jogging
SJ = 0xD8  # Stop Jogging
EF = 0xD6  # Encoder Function
EP = 0x98  # Encoder Position
FC = 0x6D  # Feed to Length with Speed Change
FD = 0x69  # Feed to Double Sensor
FE = 0xCC  # Follow Encoder
FL = 0x66  # Feed to Length
FM = 0x6A  # Feed to Sensor with Mask Distance
FO = 0x68  # Feed and Set Output
FP = 0x67  # Feed to Position
FS = 0x6B  # Feed to Sensor
FY = 0x6C  # Feed to Sensor with Safety Distance
JD = 0xA3  # Jog Disable
JE = 0xA2  # Jog Enable
MD = 0x9E  # Motor Disable
ME = 0x9F  # Motor Enable
SH = 0x6E  # Seek Home
SP = 0xA5  # Set Position
FI = 0xC0  # Filter Input
FX = 0xD3  # Filter Select Inputs
SF = 0x06  # Step Filter Freq
AD = 0xD2  # Analog Deadband
AI = 0x46  # Alarm Reset Input
AO = 0x47  # Alarm Output
AS = 0xD1  # Analog Scaling
DL = 0x42  # Define Limits
XM = 0x54  # Full Closed-loop Control Switch
SO = 0x8B  # Set Output
WI = 0x70  # Wait for Input
QX = 0x78  # Queue Load & Execute
WT = 0x6F  # Wait Time
FH = 0xDB  # Find Home
SK = 0xE1  # Stop Move & Kill Buffer, Max Decel
SKD = 0xE2  # Stop Move & Kill Buffer, Normal Decel